"""Finite-temperature dynamical-Coulomb-blockade supercurrent model.

The electromagnetic environment is represented by a parallel RC element,

    Re[Z(omega)] = R_eff / (1 + (omega R_eff C_eff)**2),

and its P(E) distribution is evaluated on an FFT grid.  In lowest-order
incoherent Cooper-pair tunnelling, the current is

    I(V) = pi e E_J**2 / hbar * [P(2 e V) - P(-2 e V)],

with E_J = hbar I_c / (2 e).
"""

from __future__ import annotations

import numpy as np
from numpy.typing import ArrayLike, NDArray
from scipy.signal import hilbert

ELEMENTARY_CHARGE_C = 1.602176634e-19
PLANCK_JS = 6.62607015e-34
HBAR_JS = PLANCK_JS / (2.0 * np.pi)
BOLTZMANN_JK = 1.380649e-23
PAIR_RESISTANCE_QUANTUM_OHM = PLANCK_JS / (2.0 * ELEMENTARY_CHARGE_C) ** 2


def get_Z_kOhm(
    nu_GHz: ArrayLike,
    Reff_kohm: float,
    Ceff_fF: float,
) -> NDArray[np.complex128]:
    """Return the complex impedance of the parallel-RC environment.

    Parameters
    ----------
    nu_GHz:
        Frequency in gigahertz.
    Reff_kohm:
        Effective parallel resistance in kilohms.
    Ceff_fF:
        Effective parallel capacitance in femtofarads.

    Returns
    -------
    numpy.ndarray
        Complex impedance in kilohms, with the shape of ``nu_GHz``.

    Notes
    -----
    The impedance is ``R_eff / (1 + 2j * pi * nu * R_eff * C_eff)``.
    ``Teff_K`` is not an argument because temperature affects the occupation
    factors in P(E), not the impedance of this circuit model.
    """
    frequency_GHz = np.asarray(nu_GHz, dtype=np.float64)
    resistance_ohm = float(Reff_kohm) * 1e3
    capacitance_F = float(Ceff_fF) * 1e-15

    if not np.all(np.isfinite(frequency_GHz)):
        raise ValueError("nu_GHz must contain only finite values.")
    if not np.isfinite(resistance_ohm) or resistance_ohm <= 0.0:
        raise ValueError("Reff_kohm must be finite and positive.")
    if not np.isfinite(capacitance_F) or capacitance_F <= 0.0:
        raise ValueError("Ceff_fF must be finite and positive.")

    angular_frequency = 2.0 * np.pi * frequency_GHz * 1e9
    impedance_ohm = resistance_ohm / (
        1.0 + 1j * angular_frequency * resistance_ohm * capacitance_F
    )
    return np.asarray(impedance_ohm * 1e-3, dtype=np.complex128)


def _parallel_rc_pe(
    Reff_ohm: float,
    Ceff_F: float,
    Teff_K: float,
    sample_count: int,
    time_step_s: float,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """Return energy in microelectronvolts and normalized P(E)."""
    angular_frequency = (
        2.0
        * np.pi
        * np.fft.fftfreq(
            sample_count,
            d=time_step_s,
        )
    )
    angular_step = 2.0 * np.pi / (sample_count * time_step_s)
    positive_frequency = angular_frequency > 0.0

    real_impedance = np.zeros_like(angular_frequency)
    omega_positive = angular_frequency[positive_frequency]
    real_impedance[positive_frequency] = Reff_ohm / (
        1.0 + (omega_positive * Reff_ohm * Ceff_F) ** 2
    )

    # J(t) = 2 int_0^inf dω Re[Z(ω)]/(R_Q ω)
    #        {(n_B + 1)[exp(-iωt) - 1] + n_B[exp(iωt) - 1]}.
    # The negative-frequency FFT bins carry the thermally activated term.
    phase_spectrum = np.zeros(sample_count, dtype=np.complex128)
    zero_temperature_weight = (
        2.0
        * real_impedance[positive_frequency]
        / PAIR_RESISTANCE_QUANTUM_OHM
        / omega_positive
        * angular_step
    )
    if Teff_K == 0.0:
        bose_occupation = np.zeros_like(omega_positive)
    else:
        thermal_argument = HBAR_JS * omega_positive / (BOLTZMANN_JK * Teff_K)
        bose_occupation = np.zeros_like(thermal_argument)
        resolvable = thermal_argument < 700.0
        bose_occupation[resolvable] = 1.0 / np.expm1(thermal_argument[resolvable])
    phase_spectrum[positive_frequency] = zero_temperature_weight * (
        bose_occupation + 1.0
    )
    negative_indices = (-np.flatnonzero(positive_frequency)) % sample_count
    phase_spectrum[negative_indices] = zero_temperature_weight * bose_occupation
    phase_correlation = np.fft.fft(phase_spectrum)
    phase_correlation -= phase_correlation[0]

    characteristic = np.exp(phase_correlation)
    pe_per_J = (
        np.fft.ifft(characteristic)
        * sample_count
        * time_step_s
        / (2.0 * np.pi * HBAR_JS)
    )
    energy_J = HBAR_JS * angular_frequency
    energy_ueV = np.fft.fftshift(energy_J) / ELEMENTARY_CHARGE_C * 1e6
    pe_per_ueV = np.fft.fftshift(pe_per_J.real) * (ELEMENTARY_CHARGE_C * 1e-6)

    # Remove the very small negative numerical ringing generated by the
    # finite FFT grid, then restore unit normalization.
    pe_per_ueV = np.maximum(pe_per_ueV, 0.0)
    pe_per_ueV /= np.trapezoid(pe_per_ueV, energy_ueV)
    return energy_ueV, pe_per_ueV


def simulate_sc_current_nA(
    V_mV: ArrayLike,
    Reff_kOhm: float,
    Ceff_fF: float,
    Ic_nA: float,
    *,
    Teff_K: float,
    sample_count: int = 2**14,
    time_step_s: float = 0.5e-12,
) -> NDArray[np.float64]:
    """Simulate incoherent Cooper-pair current in a parallel-RC environment.

    Parameters
    ----------
    V_mV:
        Junction voltage in millivolts.
    Reff_kOhm:
        Effective parallel resistance in kilohms.
    Ceff_fF:
        Effective parallel capacitance in femtofarads.
    Ic_nA:
        Critical current setting the Josephson energy, in nanoamperes.
    Teff_K:
        Effective equilibrium temperature of the electromagnetic environment,
        in kelvins. The default is zero.
    sample_count:
        Number of FFT samples. It must be an even integer of at least four.
    time_step_s:
        FFT time step in seconds.

    Returns
    -------
    numpy.ndarray
        Simulated supercurrent in nanoamperes, with the shape of ``V_mV``.

    Notes
    -----
    This is a lowest-order P(E) model. ``Reff_kOhm``, ``Ceff_fF``, and
    ``Teff_K`` determine the shape; ``Ic_nA`` enters through E_J and therefore
    sets the current amplitude quadratically.
    """
    voltage_mV = np.asarray(V_mV, dtype=np.float64)
    resistance_ohm = float(Reff_kOhm) * 1e3
    capacitance_F = float(Ceff_fF) * 1e-15
    critical_current_nA = float(Ic_nA)
    effective_temperature_K = float(Teff_K)

    if resistance_ohm <= 0.0:
        raise ValueError("Reff_kOhm must be positive.")
    if capacitance_F <= 0.0:
        raise ValueError("Ceff_fF must be positive.")
    if critical_current_nA < 0.0:
        raise ValueError("Ic_nA must be nonnegative.")
    if effective_temperature_K < 0.0:
        raise ValueError("Teff_K must be nonnegative.")
    if sample_count < 4 or sample_count % 2:
        raise ValueError("sample_count must be an even integer >= 4.")
    if time_step_s <= 0.0:
        raise ValueError("time_step_s must be positive.")

    energy_ueV, pe_per_ueV = _parallel_rc_pe(
        resistance_ohm,
        capacitance_F,
        effective_temperature_K,
        sample_count,
        time_step_s,
    )
    pair_energy_ueV = 2_000.0 * voltage_mV
    pe_forward = np.interp(
        pair_energy_ueV,
        energy_ueV,
        pe_per_ueV,
        left=0.0,
        right=0.0,
    )
    pe_backward = np.interp(
        -pair_energy_ueV,
        energy_ueV,
        pe_per_ueV,
        left=0.0,
        right=0.0,
    )

    critical_current_A = critical_current_nA * 1e-9
    josephson_energy_J = HBAR_JS * critical_current_A / (2.0 * ELEMENTARY_CHARGE_C)
    prefactor_AJ = np.pi * ELEMENTARY_CHARGE_C * josephson_energy_J**2 / HBAR_JS
    prefactor_nA_ueV = prefactor_AJ / (1e-9 * ELEMENTARY_CHARGE_C * 1e-6)
    return prefactor_nA_ueV * (pe_forward - pe_backward)


def get_PE__ueV(
    V_mV: ArrayLike,
    Isc_nA: ArrayLike,
    Teff_K: float = 0.0,
    *,
    energy_taper_fraction: float = 0.2,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """Infer the normalized P(E) distribution from a supercurrent trace.

    Parameters
    ----------
    V_mV, Isc_nA:
        Voltage and MAR-subtracted supercurrent samples. The voltage data must
        span both polarities. Any even component of the current is removed.
    Teff_K:
        Effective equilibrium temperature used for detailed balance, in
        kelvins.
    energy_taper_fraction:
        Fraction of the outer energy range over which P(E) is tapered smoothly
        to zero. This suppresses ringing caused by the finite voltage window.
        Set to zero to disable the energy taper.

    Returns
    -------
    energy_ueV:
        Symmetric energy axis in microelectronvolts.
    pe_per_ueV:
        Normalized P(E) in inverse microelectronvolts.

    Notes
    -----
    The inversion assumes equilibrium detailed balance and lowest-order
    incoherent Cooper-pair tunnelling. The unknown E_J**2 prefactor cancels
    when P(E) is normalized, so this conversion does not determine ``Ic_nA``.
    """
    voltage_mV = np.asarray(V_mV, dtype=np.float64)
    current_nA = np.asarray(Isc_nA, dtype=np.float64)
    if voltage_mV.ndim != 1 or current_nA.ndim != 1:
        raise ValueError("V_mV and Isc_nA must be one-dimensional.")
    if voltage_mV.shape != current_nA.shape:
        raise ValueError("V_mV and Isc_nA must have the same shape.")
    finite = np.isfinite(voltage_mV) & np.isfinite(current_nA)
    voltage_mV = voltage_mV[finite]
    current_nA = current_nA[finite]
    if voltage_mV.size < 9:
        raise ValueError("At least nine finite SC samples are required.")
    order = np.argsort(voltage_mV)
    voltage_mV = voltage_mV[order]
    current_nA = current_nA[order]
    if voltage_mV[0] >= 0.0 or voltage_mV[-1] <= 0.0:
        raise ValueError("V_mV must span negative and positive voltages.")
    if Teff_K < 0.0:
        raise ValueError("Teff_K must be nonnegative.")
    if not 0.0 <= energy_taper_fraction <= 1.0:
        raise ValueError("energy_taper_fraction must be between zero and one.")

    # Work on an odd, symmetric, uniform energy grid. Interpolation only makes
    # the Fourier transform well-defined; it does not add experimental detail.
    sample_count = voltage_mV.size
    if sample_count % 2 == 0:
        sample_count += 1
    maximum_voltage_mV = min(-voltage_mV[0], voltage_mV[-1])
    energy_ueV = np.linspace(
        -2_000.0 * maximum_voltage_mV,
        2_000.0 * maximum_voltage_mV,
        sample_count,
    )
    symmetric_voltage_mV = energy_ueV / 2_000.0
    forward_current = np.interp(
        symmetric_voltage_mV,
        voltage_mV,
        current_nA,
    )
    backward_current = np.interp(
        -symmetric_voltage_mV,
        voltage_mV,
        current_nA,
    )
    odd_current = 0.5 * (forward_current - backward_current)
    positive_energy = energy_ueV > 0.0
    positive_current = odd_current.copy()
    if np.nanmedian(positive_current[positive_energy]) < 0.0:
        positive_current *= -1.0
    positive_current = np.maximum(positive_current, 0.0)

    absolute_energy_ueV = np.abs(energy_ueV)
    positive_branch = np.interp(
        absolute_energy_ueV,
        energy_ueV[positive_energy],
        positive_current[positive_energy],
    )
    if Teff_K == 0.0:
        pe_per_ueV = np.where(positive_energy, positive_branch, 0.0)
    else:
        kT_ueV = 86.17333262145 * Teff_K
        detailed_balance_denominator = -np.expm1(-absolute_energy_ueV / kT_ueV)
        pe_positive = np.divide(
            positive_branch,
            detailed_balance_denominator,
            out=np.zeros_like(positive_branch),
            where=detailed_balance_denominator > 0.0,
        )
        zero_index = sample_count // 2
        pe_positive[zero_index] = 0.5 * (
            pe_positive[zero_index - 1] + pe_positive[zero_index + 1]
        )
        pe_per_ueV = np.where(
            energy_ueV >= 0.0,
            pe_positive,
            pe_positive * np.exp(-absolute_energy_ueV / kT_ueV),
        )

    normalization = np.trapezoid(pe_per_ueV, energy_ueV)
    if not np.isfinite(normalization) or normalization <= 0.0:
        raise ValueError("The SC trace does not produce a normalizable P(E).")
    pe_per_ueV /= normalization

    # A finite voltage window is a rectangular truncation of P(E), whose sharp
    # edges cause Fourier ringing. Smoothly bring the outer part of the energy
    # distribution to zero before transforming it.
    if energy_taper_fraction > 0.0:
        maximum_absolute_energy_ueV = float(np.max(np.abs(energy_ueV)))
        taper_start_ueV = (
            1.0 - energy_taper_fraction
        ) * maximum_absolute_energy_ueV
        energy_taper = np.ones_like(energy_ueV)
        edge = np.abs(energy_ueV) > taper_start_ueV
        edge_coordinate = (
            np.abs(energy_ueV[edge]) - taper_start_ueV
        ) / (maximum_absolute_energy_ueV - taper_start_ueV)
        energy_taper[edge] = 0.5 * (1.0 + np.cos(np.pi * edge_coordinate))
        pe_per_ueV *= energy_taper
        pe_per_ueV /= np.trapezoid(pe_per_ueV, energy_ueV)

    return energy_ueV, pe_per_ueV


def _pe_to_impedance(
    energy_ueV: NDArray[np.float64],
    pe_per_ueV: NDArray[np.float64],
    nu0_GHz: float,
    frequency_points: int,
    time_taper_fraction: float,
) -> tuple[NDArray[np.float64], NDArray[np.complex128]]:
    """Convert a normalized P(E) distribution to effective impedance."""
    sample_count = energy_ueV.size

    energy_step_ueV = float(np.mean(np.diff(energy_ueV)))
    energy_step_J = energy_step_ueV * 1e-6 * ELEMENTARY_CHARGE_C
    characteristic = (
        np.fft.fftshift(np.fft.fft(np.fft.ifftshift(pe_per_ueV))) * energy_step_ueV
    )
    time_s = np.fft.fftshift(np.fft.fftfreq(sample_count, d=energy_step_J)) * PLANCK_JS
    positive_time = time_s >= 0.0
    time_s = time_s[positive_time]
    characteristic = characteristic[positive_time]

    reliable = np.abs(characteristic) > 1e-4
    unreliable_indices = np.flatnonzero(~reliable)
    stop = unreliable_indices[0] if unreliable_indices.size else time_s.size
    stop = min(time_s.size, max(stop, min(16, time_s.size)))
    time_s = time_s[:stop]
    phase = np.unwrap(np.angle(characteristic[:stop]))
    phase -= phase[0]
    phase_derivative = np.gradient(phase, time_s)

    taper = np.ones_like(time_s)
    if time_taper_fraction > 0.0:
        taper_start = int((1.0 - time_taper_fraction) * time_s.size)
        taper_start = min(taper_start, time_s.size - 1)
        taper_coordinate = np.linspace(0.0, 1.0, time_s.size - taper_start)
        taper[taper_start:] = 0.5 * (
            1.0 + np.cos(np.pi * taper_coordinate)
        )

    # Extend the Kramers--Kronig grid beyond the returned band to reduce edge
    # artefacts in Im[Z]. Re[Z] is even and Im[Z] is odd for a causal circuit.
    extension_factor = 4
    extended_points = extension_factor * (frequency_points - 1) + 1
    positive_frequency_Hz = np.linspace(
        0.0,
        extension_factor * nu0_GHz * 1e9,
        extended_points,
    )
    cosine = np.cos(2.0 * np.pi * time_s[:, None] * positive_frequency_Hz[None, :])
    real_impedance_ohm = (
        -PAIR_RESISTANCE_QUANTUM_OHM
        / np.pi
        * np.trapezoid(
            phase_derivative[:, None] * taper[:, None] * cosine,
            time_s,
            axis=0,
        )
    )
    symmetric_real_impedance = np.concatenate(
        (real_impedance_ohm[:0:-1], real_impedance_ohm)
    )
    symmetric_imaginary_impedance = -np.imag(hilbert(symmetric_real_impedance))
    imaginary_impedance_ohm = symmetric_imaginary_impedance[extended_points - 1 :]

    returned_slice = slice(0, frequency_points)
    frequency_GHz = positive_frequency_Hz[returned_slice] * 1e-9
    impedance_kOhm = (
        real_impedance_ohm[returned_slice]
        + 1j * imaginary_impedance_ohm[returned_slice]
    ) * 1e-3
    return frequency_GHz, impedance_kOhm


def get_Zw_kOhm(
    V_mV: ArrayLike,
    Isc_nA: ArrayLike,
    nu0_GHz: float,
    *,
    frequency_points: int = 401,
    energy_taper_fraction: float = 0.2,
    time_taper_fraction: float = 0.4,
) -> tuple[NDArray[np.float64], NDArray[np.complex128]]:
    """Infer effective complex impedance from a supercurrent trace.

    ``nu0_GHz`` is the largest returned frequency. The inversion uses the
    zero-temperature P(E) reconstruction and returns ``frequency_points``
    equally spaced frequencies, including zero.
    """
    if nu0_GHz <= 0.0:
        raise ValueError("nu0_GHz must be positive.")
    if frequency_points < 16:
        raise ValueError("frequency_points must be at least 16.")
    if not 0.0 <= time_taper_fraction <= 1.0:
        raise ValueError("time_taper_fraction must be between zero and one.")

    energy_ueV, pe_per_ueV = get_PE__ueV(
        V_mV,
        Isc_nA,
        energy_taper_fraction=energy_taper_fraction,
    )
    return _pe_to_impedance(
        energy_ueV,
        pe_per_ueV,
        nu0_GHz,
        frequency_points,
        time_taper_fraction,
    )


def sc_to_pe_and_impedance(
    V_mV: ArrayLike,
    Isc_nA: ArrayLike,
    *,
    temperature_mK: float = 0.0,
    maximum_frequency_GHz: float = 100.0,
    frequency_points: int = 401,
    energy_taper_fraction: float = 0.2,
    time_taper_fraction: float = 0.4,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.complex128],
]:
    """Infer P(E) and impedance; retained for backward compatibility."""
    energy_ueV, pe_per_ueV = get_PE__ueV(
        V_mV,
        Isc_nA,
        Teff_K=temperature_mK * 1e-3,
        energy_taper_fraction=energy_taper_fraction,
    )
    if maximum_frequency_GHz <= 0.0:
        raise ValueError("maximum_frequency_GHz must be positive.")
    if frequency_points < 16:
        raise ValueError("frequency_points must be at least 16.")
    if not 0.0 <= time_taper_fraction <= 1.0:
        raise ValueError("time_taper_fraction must be between zero and one.")
    frequency_GHz, impedance_kOhm = _pe_to_impedance(
        energy_ueV,
        pe_per_ueV,
        maximum_frequency_GHz,
        frequency_points,
        time_taper_fraction,
    )
    return energy_ueV, pe_per_ueV, frequency_GHz, impedance_kOhm


__all__ = [
    "get_PE__ueV",
    "get_Z_kOhm",
    "get_Zw_kOhm",
    "sc_to_pe_and_impedance",
    "simulate_sc_current_nA",
]
